package com.xephyrka.liora.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class representing a category or container for organizing tasks.
 * Users can create multiple lists to group related tasks (e.g., "Work", "Personal").
 */
@Entity(tableName = "task_lists")
data class TaskList(
    /** Unique identifier for the task list, automatically generated by the database. */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    /** The user-defined name of the list. */
    val name: String,
    /** The timestamp (in milliseconds) when the list was originally created. */
    val createdAt: Long = System.currentTimeMillis()
)
