package com.xephyrka.liora.data.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Data class representing a sub-item of a main task.
 * Subtasks are tied to a parent [Task] and can be independently marked as completed.
 */
@Entity(
    tableName = "subtasks",
    foreignKeys = [
        ForeignKey(
            entity = Task::class,
            parentColumns = ["id"],
            childColumns = ["taskId"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class SubTask(
    /** Unique identifier for the subtask, automatically generated by the database. */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    /** The identifier of the parent task this subtask belongs to. */
    val taskId: Int,
    /** The descriptive title or content of the subtask. */
    val title: String,
    /** Whether the subtask has been completed by the user. */
    val isCompleted: Boolean = false
)

/**
 * Data class representing a primary unit of work or information.
 * Tasks can be simple notes, one-time tasks with reminders, or recurring events.
 */
@Entity(tableName = "tasks")
data class Task(
    /** Unique identifier for the task, automatically generated by the database. */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    /** The main title or heading of the task. */
    val title: String,
    /** Detailed description or note associated with the task. */
    val content: String = "",
    /** The ID of the [TaskList] this task is categorized under. */
    val listId: Int,
    /** The nature of the task, distinguishing between actionable items and static notes. */
    val itemType: ItemType = ItemType.TASK,
    /** The timestamp (in milliseconds) for when the user should be reminded of this task. */
    val reminderTime: Long? = null,
    /** Whether the task has been marked as finished. */
    val isCompleted: Boolean = false,
    /** Whether this task should repeat on a regular schedule. */
    val isRecurring: Boolean = false,
    /** The frequency multiplier for recurrence (e.g., every '2' weeks). */
    val recurrenceInterval: Int = 1,
    /** The base unit of time for the recurrence schedule. */
    val recurrenceUnit: RecurrenceUnit = RecurrenceUnit.DAY,
    /** A comma-separated string of day numbers (1-7) for weekly recurrence (e.g., "1,3,5"). */
    val recurrenceDaysOfWeek: String? = null,
    /** An optional end date for the recurrence schedule. */
    val recurrenceEndDate: Long? = null,
    /** An optional limit on the total number of times a task should recur. */
    val recurrenceEndOccurrences: Int? = null
)

/**
 * Defines the functional categories a task can belong to.
 */
enum class ItemType {
    /** An actionable item that can have a reminder and subtasks. */
    TASK,
    /** A static piece of information without scheduled reminders. */
    NOTE
}

/**
 * Specifies the units of time used to calculate recurrence schedules.
 */
enum class RecurrenceUnit {
    /** The task recurs after a set number of days. */
    DAY,
    /** The task recurs on specific days of the week. */
    WEEK,
    /** The task recurs on the same day every month. */
    MONTH
}
